### ISSUE TITLE
Apache seems to prevent response header injection

### ISSUE THREAD

**Issue by clemblanco** [spatie/laravel-cors#10]
Hi,

Everything works fine locally using Docker and an Apache 2.2 image however on my staging server (also Apache 2.2) the response headers are not injected properly?

I managed to get those headers injected manually by adding the following to the top of my `/public/.htaccess` file:

```
<IfModule mod_headers.c>
    Header set Access-Control-Allow-Origin "*"
    Header set Access-Control-Allow-Methods "GET"
    Header set Access-Control-Allow-Headers "Accept, Content-Type, Authorization"
</IfModule>
```

but here I'm king of loosing the interest in using your package :/

Any idea of what kind of Apache configuration would be required to allow Laravel to inject those headers in my responses?

Thanks!

**Comment by AlexVanderbist** [comment]
Hi @clementblanco, we're mainly using NGINX over here and my knowledge of Apache is limited. However I couldn't find any information about Apache not allowing headers to be set by PHP. Are you sure they're not being overwritten in some `.htaccess` file or the config?

Maybe someone else using Apache can shed some light on this.

**Comment by TheAlexLichter** [comment]
I'm using Apache regularly, but for me, `laravel-cors` does what it should.
