### ISSUE TITLE
own profile example doesn't work

### ISSUE THREAD

**Issue by rob-2018** [spatie/laravel-cors#16]
Using the example from the README of creating your own profile does not work. The error is
```  [Spatie\Cors\Exceptions\InvalidCorsProfile]                                  
  The configured cors profile in `App\Services\Cors\UserBasedCorsProfile` is   
  invalid. A valid cors profile extends `Spatie\Cors\CorsProfile\DefaultProfile`                                                                        
```
What's wrong?

**Comment by freekmurze** [comment]
Try running `php artisan config:clear` and try again.

Does your profile extend `Spatie\Cors\CorsProfile\DefaultProfile`?

Could you post your profile class and config file?

**Comment by rob-2018** [comment]
Clearing the cache didn't make a difference.

Yes my profile extends DefaulProfile (and has the correct path as far as I can tell). I just use the example from the README, here are the relevant parts.

config/cors.php:
```
return [
    'cors_profile' => App\Services\Cors\UserBasedCorsProfile::class,
    ...
```
MyCorsProfile.php:
```
namespace App\Services\Cors;

use Spatie\Cors\CorsProfile\DefaultProfile;

class UserBasedCorsProfile extends DefaultProfile
{
    public function allowOrigins(): array
    {
        return ['localhost'];
    }
}
```
I double checked all namespace paths but can't spot typo's. If in config/cors.php I change `cors_profile' => Spatie\Cors\CorsProfile\DefaultProfile::class,` then everything works fine. My feeling is I'm missing something basic here...

**Comment by TVke** [comment]
Hi @rob-2018 

I can not find a problem, maybe a composer dump would help. If it does not work, know that you can add the `localhost` to the `cors.php` config file to have the same results and you avoid the error.

Hope this helps

greetings
Thomas
