### ISSUE TITLE
Getting asked about extra headers

### ISSUE THREAD

**Issue by fgilio** [spatie/laravel-cors#20]
Hi!

We had to add 2 extra headers to the `allow_headers` array:  'X-Requested-With', 'X-CSRF-TOKEN'.
Is that a common thing? Here I have a screenshot of one of the error messages:
<img width="1270" alt="screen shot 2018-03-12 at 5 28 26 pm" src="https://user-images.githubusercontent.com/6857732/37348792-bdec4984-26b3-11e8-8a59-44ec00846c42.png">

Thanks!

**Comment by kohenkatz** [comment]
You need to [add them to the config file](https://github.com/spatie/laravel-cors/blob/4e1fb9cb40229cd6d6b46f0231a7912b6bc604f2/config/cors.php#L33-L38).
