### ISSUE TITLE
config file doesn't publish

### ISSUE THREAD

**Issue by taufpate** [spatie/laravel-cors#3]
php artisan vendor:publish --provider="Spatie\Cors\CorsServiceProvider" --tag="cors"

doesn't generate any config file

**Comment by freekmurze** [comment]
I've updated the readme, correct command is

```
php artisan vendor:publish --provider="Spatie\Cors\CorsServiceProvider" --tag="config"
```

Please note that this package is work in progress. A stable release will be tagged in the next few days.
