### ISSUE TITLE
Target [Spatie\Cors\CorsProfile\CorsProfile] is not instantiable while building [Spatie\Cors\Cors].

### ISSUE THREAD

**Issue by jwillz21** [spatie/laravel-cors#38]
I'm not familiar with CORS. Someone had added it to this project and I don't know to much about it. I've been trying to deploy a dev version of this project to a live server but I am getting this error.

```Target [Spatie\Cors\CorsProfile\CorsProfile] is not instantiable while building [Spatie\Cors\Cors].```

I haven't found to much info online about this error. I did however come across a thread that said I need to add the provider to my ```config/app.php``` however this brought me to a new error when using  php artisan commands.

```Class 'Spatie\Permission\PermissionServiceProvider not found```

**Comment by freekmurze** [comment]
It seems like the package is not installed correctly. The  `PermissionServiceProvider` is seemingly related to another problem. Please refer to the installation instructions. If you have questions on installation please ask them on a public forum like the laracasts forum, laravel.io or StackOverflow.
