### ISSUE TITLE
Lumen 5.7 support?

### ISSUE THREAD

**Issue by nomayonnaise** [spatie/laravel-cors#40]
Has lumen support been abandoned? The requirements in composer.json have been changed from

```
"illuminate/support": "5.5.*|5.6.*"
```
to
```
"laravel/framework": "5.5.*|5.6.*|5.7.*"
```

which means, there's no way to use this with lumen 5.7

**Comment by oanhnn** [comment]
@nomayonnaise Support Lumen was comeback !!! Can you close issue?
