### ISSUE TITLE
Response to preflight request doesn't pass access control check

### ISSUE THREAD

**Issue by boldstar** [spatie/laravel-cors#41]
Using this package on my local enviroment works great. Currently when making any api calls to my backend in my production environment throws the following alarm

```
my url request has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.
```

I have tried everything I can find to troubleshoot this issue with no luck. Here is my cors.php file
```
<?php

return [

    /*
     * A cors profile determines which origins, methods, headers are allowed for
     * a given requests. The `DefaultProfile` reads its configuration from this
     * config file.
     *
     * You can easily create your own cors profile.
     * More info: https://github.com/spatie/laravel-cors/#creating-your-own-cors-profile
     */
    'cors_profile' => Spatie\Cors\CorsProfile\DefaultProfile::class,

    /*
     * This configuration is used by `DefaultProfile`.
     */
    'default_profile' => [

        'allow_credentials' => false,

        'allow_origins' => [
            'https://*.myurl.com',
             '*'
        ],

        'allow_methods' => [
            'POST',
            'GET',
            'OPTIONS',
            'PUT',
            'PATCH',
            'DELETE',
        ],

        'allow_headers' => [
            'Content-Type',
            'X-Auth-Token',
            'Origin',
            'Authorization',
        ],

        'expose_headers' => [
            'Cache-Control',
            'Content-Language',
            'Content-Type',
            'Expires',
            'Last-Modified',
            'Pragma',
        ],

        'forbidden_response' => [
            'message' => 'Forbidden (cors).',
            'status' => 403,
        ],

        /*
         * Preflight request will respond with value for the max age header.
         */
        'max_age' => 60 * 60 * 24,
    ],
];
```
I have it registered in the global middle ware
```
protected $middleware = [
        \App\Http\Middleware\CheckForMaintenanceMode::class,
        \Illuminate\Foundation\Http\Middleware\ValidatePostSize::class,
        \App\Http\Middleware\TrimStrings::class,
        \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
        \App\Http\Middleware\TrustProxies::class,
        \Spatie\Cors\Cors::class,
        Middleware\PreflightResponse::class,
    ];
```
the middleware\preflightresponse::class was one of my attemps to fix the issue but still no luck.

Any help would be greatly appreciated!!

**Comment by RaGreen** [comment]
Downgrade, some unknown changes in Laravel broke CORS from spatie and barryvdh. Creating own middleware seems to doesn't work too.

**Comment by boldstar** [comment]
The original issue that was posted ended up not being a spatie/laravel-cors issue at all. The package works great on local and production. thanks. closing this issue.

**Comment by onurkose** [comment]
Today I made it possible to work with Laravel 5.8 but I think it's not a generic problem and the reason people having difficulties to address them because of the laravel's exception handlers doesn't give errors on certain points.

In my case a new library (Moontoast/Math) added to Laravel giving a missing function error (bcadd) and there was not a single error exception at all. To find out what was wrong I've gone too far on http kernel's roots and put some dd's on Pipeline's exception handlers and that was it, just a missing function. After all my nginx and console were using different php versions and bcmath extension has been loaded onto non-nginx version so it was the reason of the problem.
