### ISSUE TITLE
1.3.3 to 1.4.0 should be a major instead of minor upgrade.

### ISSUE THREAD

**Issue by pcmulder** [spatie/laravel-cors#45]
Changing the PHP requirement from 7.1 to 7.2 will break on a lot of production servers. And the default composer versioning will allow it. Which is why I think it is by the definition of SemVer not a change that  "add(s) functionality in a backwards-compatible manner". 

Can this be changed?

**Comment by freekmurze** [comment]
Actually Compose will check for the installed PHP version. So this isn’t a breaking change.
