### ISSUE TITLE
Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by davi5e** [spatie/laravel-cors#46]
My API is in a different domain than the main application and I can't seem to get CORS to work correctly....

In `app/Providers/RouteServiceProvider.php`, I changed the domain:
```php
    protected function mapApiRoutes()
    {
        Route::domain('api.' . parse_url(config('app.url'))['host'])
            ->middleware('api')
            ->namespace($this->namespace)
            ->group(base_path('routes/api.php'));
    }
```
So that now my API resides in **http://api.exemple.com**.

Following the instructions of the package, I added the middleware in `app/Http/Kernel.php`:
```php
    protected $middlewareGroups = [
        // [...]
        'api' => [
            'cors',
            'throttle:60,1',
            'bindings',
        ],
    ];

    protected $routeMiddleware = [
        // [...]
        'cors' => \Spatie\Cors\Cors::class,
    ];
```

To test it, I manually added all Auth routes to `config/api.php` and `config/web.php`, as in:

**config/web.php**
```php
// [...]
Route::get('login', 'Auth\LoginController@showLoginForm');
Route::get('register', 'Auth\RegisterController@showRegistrationForm');
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
```

**config/api.php**
```php
// [...]
Route::post('login', 'Auth\LoginController@login')->name('login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');
Route::post('register', 'Auth\RegisterController@register')->name('register');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');
```

For the sake of simplicity, I'm using the default profile with `'allow_credentials' => true,` (from `config/cors.php`), which should allow pretty much any request. I'm also using a local DNS  server configured using [dnsmasq](http://www.thekelleys.org.uk/dnsmasq/doc.html) — but this may be irrelevant since the same behavior occurs in my production website (with an actual domain and IP mapped to a DNS A Record).

Testing the login form provided by `php artisan make:auth` in a VueJs page, the error reported by Axios is:

> Access to XMLHttpRequest at 'http://api.example.com/login' from origin 'http://example.com:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Using Chrome, the only request I get in the Network tab is:
```
Request URL: http://api.exemple.com/login
Request Method: OPTIONS
Status Code: 200 OK
Remote Address: 127.0.0.1
Referrer Policy: no-referrer-when-downgrade

[Requested Headers]
Access-Control-Request-Headers: access-control-allow-credentials,access-control-allow-origin,x-requested-with
Access-Control-Request-Method: POST
DNT: 1
Origin: http://exemple.com:8080
Referer: http://exemple.com:8080/login
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36

[Response Headers]
Allow: POST
Cache-Control: no-cache, private
Connection: keep-alive
Content-Encoding: gzip
Content-Type: text/html; charset=UTF-8
Date: Tue, 12 Mar 2019 18:12:53 GMT
Server: nginx
Transfer-Encoding: chunked
Vary: Accept-Encoding
X-UA-Compatible: IE=Edge
```

Finally, I debugged the Axios request to find the request that (should?) trigger the CORS handler (log from the [interceptor](https://github.com/axios/axios#interceptors)):
```
url: "http://api.exemple.com/login"
method: "post"
headers:
    Accept: "application/json"
    Access-Control-Allow-Credentials: "true"
    Access-Control-Allow-Origin: "*"
    Content-Type: "application/x-www-form-urlencoded"
    X-Requested-With: "XMLHttpRequest"
```

And now I'm lost... I know the package works with the main domain (in this example, example.com), but I can't seem to find out why it's not working :/

Anyhow, is it even supposed to work in a subdomain or did I get any configuration wrong?

Regards

Edit: Please disregard a possible sessions problem that may arise with this configuration. The point is getting CORS to work so I can continue building my API. It's also easier to reproduce using these routes...

**Comment by ghost** [comment]
I had the same issue, moving cors middleware under global middleware configuration (as said in README) solved my issue (don't know why)

**Comment by davi5e** [comment]
Turns out, I had another, unrelated, problem.

All these subdomains really mess things up in [tightenco/ziggy](https://github.com/tightenco/ziggy) and my Axios call was missing the `8080` port in the Request.

I have not tried to replicate the reported behavior since I applied @clmnt-wisepops 's solution and it worked.

I'll be closing this issue.

**Comment by davi5e** [comment]
If anyone ever needs it, this is [the issue over in tightenco/ziggy](https://github.com/tightenco/ziggy/issues/208).

**Comment by tirta-keniten** [comment]
> I had the same issue, moving cors middleware under global middleware configuration (as said in README) solved my issue (don't know why)

It works, but just figure out that cors middleware must run first then I add ``\Spatie\Cors\Cors::class,`` on ``$middlewarePriority``.

```
protected $middlewarePriority = [
        \Spatie\Cors\Cors::class,
        \Illuminate\Session\Middleware\StartSession::class,
        \Illuminate\View\Middleware\ShareErrorsFromSession::class,
        \App\Http\Middleware\Authenticate::class,
        \Illuminate\Routing\Middleware\ThrottleRequests::class,
        \Illuminate\Session\Middleware\AuthenticateSession::class,
        \Illuminate\Routing\Middleware\SubstituteBindings::class,
        \Illuminate\Auth\Middleware\Authorize::class,
    ];
```
