### ISSUE TITLE
301 Redirect to http - CORS Request Failed

### ISSUE THREAD

**Issue by zlanich** [spatie/laravel-cors#47]
I'm running into a strange issue with my CORS requests sending back a 301 redirect to the http variant of my endpoint(s). 

Small bit of context:

I have an SPA built in React, using the `fetch()` api with `cors` mode on. The ui is hosted on `https://admin.MYDOMAIN.com` and the api is at `https://app.MYDOMAIN.com`

Here's some info:

1. I'm on Heroku (aka. AWS), and behind load balancers, but my TrustedProxy seems to be operating correctly - Screenshot: ![trusted-proxy](https://user-images.githubusercontent.com/1522665/54409415-09483080-46bd-11e9-863a-c5dac9cbe4e5.png) - I don't have URL or redirect issues anywhere else.

Here's my TrustProxies config:
``` php
class TrustProxies extends Middleware
{
    protected $proxies = '*';

    protected $headers = Request:: HEADER_X_FORWARDED_AWS_ELB;
}
```

2. I do not have this issue in my local environment (http or https)

3. I've tried moving the CORS middleware around (ie. before TrustProxies, etc), and seems to have no affect.

4. I had this same issue with https://github.com/barryvdh/laravel-cors

Here is the console error: ![console-failed](https://user-images.githubusercontent.com/1522665/54409439-1ebd5a80-46bd-11e9-8f2e-85e32c59199d.png)

Here is the network tab that shows the 301: ![network](https://user-images.githubusercontent.com/1522665/54409450-2da40d00-46bd-11e9-8e98-4b877f64bec0.png)

Here's my cors.php config: 
```php
return [

    'cors_profile' => Spatie\Cors\CorsProfile\DefaultProfile::class,

    'default_profile' => [

        'allow_credentials' => false,

        'allow_origins' => [
            'https://admin.MYDOMAIN.com',
            'http://admin.MYDOMAIN.test',
            'https://admin.MYDOMAIN.test',
            'http://localhost:3000',
        ],

        'allow_methods' => [
            'POST',
            'GET',
            'OPTIONS',
            'PUT',
            'PATCH',
            'DELETE',
        ],

        'allow_headers' => [
            'Content-Type',
            'X-Auth-Token',
            'Origin',
            'Authorization',
        ],

        'expose_headers' => [
            'Cache-Control',
            'Content-Language',
            'Content-Type',
            'Expires',
            'Last-Modified',
            'Pragma',
        ],

        'forbidden_response' => [
            'message' => 'Forbidden (cors).',
            'status' => 403,
        ],

        'max_age' => 60 * 60 * 24,
    ],
];
```

I've spent DAYS on this, and I'm at a loss. Any help would be a godsend. Thank you!

**Comment by samatcd** [comment]
We're also hitting this issue. Was there ever any resolution or explanation as to why this might be happening?
