### ISSUE TITLE
How does this work with a different middleware?

### ISSUE THREAD

**Issue by francoism90** [spatie/laravel-cors#48]
No ORIGIN headers are used when using a different [middleware driver](https://github.com/tymondesigns/jwt-auth):
```
'defaults' => [
        'guard' => 'api',
        'passwords' => 'users',
    ],
],

...

'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'jwt',
            'provider' => 'users',
            'hash' => false,
        ],
    ],
```

It seems additional steps are needed to provide the CORS-headers in the requests, is this true?

Thanks!

**Comment by atymic** [comment]
Can you show your middleware configuration?
It should still work correctly irrespective of what auth driver is used.

**Comment by atymic** [comment]
ping @francoism90

**Comment by francoism90** [comment]
@atymic Sorry, working on other stuff at the moment, will re-open if needed.
