### ISSUE TITLE
Article dead link

### ISSUE THREAD

**Issue by mskenderian-wps** [spatie/laravel-cors#53]
in the Readme:

Read this excellent article on the subject if you want to understand what CORS is all about.

the link https://spring.io/understanding/CORS is dead.

**Comment by atymic** [comment]
Perhaps we could update it to the mozilla docs?
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by freekmurze** [comment]
Sure, send a PR 👍
