### ISSUE TITLE
please add support for '*' for allowed headers

### ISSUE THREAD

**Issue by vesper8** [spatie/laravel-cors#55]
like many users I had been using https://github.com/barryvdh/laravel-cors for years and decided to switch to your package instead because it's more actively supported and because I have great confidence in all Spatie packages

the default configuration for the other laravel-cors project has '*' for allowed headers and allowed methods: https://github.com/barryvdh/laravel-cors/blob/master/config/cors.php

After switching to your package I was surprised to see that your default configuration broke my apps as my apps required many additional entries to be added to the allow_headers array

after adding a few manually and struggling to understand whether they are case sensitive (they appear to be) and running into more situations where more custom entries need to be added, I really found myself wishing you supported '*'

I see you added '*' support for allow_origins which was quite welcome. I would really appreciate if you did the same for allow_headers and while you're at it why not also allow_methods

thank you, really appreciate you releasing this package

**Comment by freekmurze** [comment]
Thanks for the kind words. Feel free to send a PR with tests to add this to the package 👍
