### ISSUE TITLE
Preflight Request 204 needs to be really empty

### ISSUE THREAD

**Issue by mipapo** [spatie/laravel-cors#60]
204 needs to be an empty response - This Merge can result in duplicate Requests in the end! (at least in Chrome)
If you want to send "Preflight OK" you will need to send a 200.
Firefox is able to handle this, but Google Chrome not

https://github.com/spatie/laravel-cors/pull/52

**Comment by mipapo** [comment]
If you want to send "Preflight OK" you will need to send a 200.
Firefox is able to handle this, but Google Chrome not

**Comment by freekmurze** [comment]
Fixed in the latest version of the package.
