### ISSUE TITLE
Configuration to whitelist specific servers on dev/local vs production

### ISSUE THREAD

**Issue by connecteev** [spatie/laravel-cors#62]
I want to use this package to prevent access from all servers but mine.
 
On production:
I want to allow Ajax and Axios requests from my front-end server, myserver.com:3000, and block API access from everywhere else. 
On dev and local, I want to allow API access from localhost:3000 and 127.0.0.1:3000 only.

This is how I have (currently) configured the package (in config/cors.php) 
Is this the best way to do that?

```
// config/cors.php

    'default_profile' => [

        'allow_origins' => in_array(env('APP_ENV'), ['local', 'dev']) ? [
            //'*',
            'http://127.0.0.1:3000',
            'http://localhost:3000',
            'https://127.0.0.1:3000',
            'https://localhost:3000',
        ] : [
            'http://myserver.com:3000',
            'https://myserver.com:3000',
        ],

```

**Comment by riasvdv** [comment]
That's an okay solution.

Alternatively you could also create an env key for `CORS_ALLOW_ORIGINS` and just have a comma-separated list of domains in there:

```
CORS_ALLOW_ORIGINS=http://myserver.com:3000,https://myserver.com:3000
```

In your config file you can then do a simple `explode` on them:

```php
'allow_origins' => explode(',', env('CORS_ALLOW_ORIGINS')),
```

**Comment by connecteev** [comment]
@riasvdv thanks, makes sense. I tried this out, and unfortunately this (both your solution and mine) will block all client-side ajax requests, even legitimate ones.

When an ajax request comes in from the front-end client to the Laravel API (running laravel-cors), how do you ensure it's only coming from a client running my website, and not from some other domain?

**Comment by riasvdv** [comment]
Might be the ports that are causing the issue
