### ISSUE TITLE
Does this package have a dependency on Laravel Passport to fix CORS errors?

### ISSUE THREAD

**Issue by connecteev** [spatie/laravel-cors#63]
Even after installing this package in my Laravel backend API layer, I am currently seeing a CORS error when my front-end tries to access the Laravel backend via APIs because of a missing "Access-Control-Allow-Origin" header.

Note: The error goes away if I include laravel/passport AND this package (laravel-cors) in my composer.json and install them.
Without **both** of them, I see a CORS error. Is this package supposed to work by itself as a standalone, or does it need Laravel Passport? Anyone facing this issue?

**Comment by freekmurze** [comment]
I haven't come across this issue yet. This package is supposed to work by itself as a standalone.

**Comment by connecteev** [comment]
Hmm, strange why I am seeing this. I'll have to try the other cors package and report back what I find once I've tested it.

**Comment by zolotov88** [comment]
Same problem

**Comment by connecteev** [comment]
agreed, would be nice if this worked as a standalone.

**Comment by zolotov88** [comment]
Sorry, it was another problem)
