### ISSUE TITLE
Rarely throws a BindingResolutionException

### ISSUE THREAD

**Issue by meijdenmedia** [spatie/laravel-cors#64]
I very rarely receive a BindingResolutionException. Can not figure out why.
Do you guys have any idea of what could be wrong?

I'm currently running Laravel 5.5 with spatie/laravel-cors 1.4.0

![Screenshot 2019-08-07 at 08 29 57](https://user-images.githubusercontent.com/15846780/62599883-b9793880-b8ed-11e9-89e1-12b9ef566d02.png)

**Comment by meijdenmedia** [comment]
Anyone else having these issues? Running Laravel 5.8 now and still facing these issues very randomly.

**Comment by freekmurze** [comment]
I've not come accross this problem myself. I welcome a PR that fixes it.

**Comment by meijdenmedia** [comment]
I would love to submit a PR. Do you have any clue how to find out what the underlying issue is? Or where to look?

**Comment by freekmurze** [comment]
Not really, I haven't encountered this error myself yet.

**Comment by litan1106** [comment]
I also ran into this issue with phpunit. It worked fine after I removed the bootstrap/cache files.

**Target [Spatie\Cors\CorsProfile\CorsProfile] is not instantiable while building [Spatie\Cors\Cors].**
