### ISSUE TITLE
Unable to use it with the new Laravel v6.0

### ISSUE THREAD

**Issue by anabeto93** [spatie/laravel-cors#68]
Was initially using it with laravel 5.8.* and eventually chose to upgrade to the latest v6.0 and I'm meeting with challenges doing the installation.

Below is a sample of the errors encountered.

- don't install illuminate/support v5.5.0|don't install laravel/framework v6.0.0
- Installation request for laravel/framework (locked at v6.0.0, required as ^6.0) -> satisfiable by laravel/framework[v6.0.0].
    - Installation request for spatie/laravel-cors ^1.5 -> satisfiable by spatie/laravel-cors[1.5.0, 1.5.1, 1.5.2].

**Comment by HollyIT** [comment]
Until they get around to updating it, I've got a fork running on 6.0. All I had to do was modify the laravel framework requirement in Composer and everything has been working fine.

https://github.com/HollyIT/laravel-cors

**Comment by anabeto93** [comment]
I think you need to update the docs to reflect the installation that points to your forked repo.

 composer require hollyit/laravel-cors ? or how does one go about using it.

How I go it to work is more of a hack. I downloaded the repo and extracted the `src` directory to `app/Extensions/Cors` and then went ahead to change all namespaces from `Spatie` to `App\Extensions`.

**Comment by HollyIT** [comment]
It was only a quick thing so I could quickly use it on a current project. I'm sure Spatie will have it updated in the next day or so. In the meantime you can just add the fork as a repository in your composer.json:

```
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/HollyIT/laravel-cors"
        }
    ],
```

Then just update the require in composer.json to:

`
   "spatie/laravel-cors": "dev-master",
`

And then run composer update. That way when the actually package gets updated, just delete the repositories section and point the require to the new version.

**Comment by anabeto93** [comment]
It worked like a charm.

But I'll leave this open till tomorrow. Hopefully, @freekmurze sees this and does the update.

Thank you @HollyIT 
![hollyIt](https://user-images.githubusercontent.com/7607657/64211439-b6924900-ce95-11e9-8427-77e33a0eb91b.PNG)
