### ISSUE TITLE
Applying to single route doesn't seem to work

### ISSUE THREAD

**Issue by simplenotezy** [spatie/laravel-cors#76]
I have tried to apply the cors to a single route using this:

    $routeMiddleware = [
        'cors' => \Spatie\Cors\Cors::class
    ]

And in my web.php:

    Route::get('/test', function() {
    	    return 'something';
    })->middleware('cors');

I still get error: 

    Access to XMLHttpRequest at 'https://laravel.test/test' from origin 'https://domain.test' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

If I add the cors to the global `$middleware` array it works.

**Comment by mberneis** [comment]
I have a similar problem - I like to apply the middleware only to a single controller
```
 public function __construct()
    {
        $this->middleware(['auth:api','cors']);
   }
```
and get the cors error - same as @simplenotezy case - if I enable in (global) `$middleware` array it works

**Comment by freekmurze** [comment]
I currently don't have the time to look at this issue soon, but I'd accept a PR that fixes this.

**Comment by liran-co** [comment]
Can confirm this is an issue. Tried to dig into why, but everything seems to check out. @freekmurze any idea?

**Comment by jeremynikolic** [comment]
I'll give it a look

**Comment by cshawaus** [comment]
I have had a look using Laravel v6.15.1 but wasn't able to replicate the issue.

@simplenotezy Which version of Laravel are you using?

**Comment by jeremynikolic** [comment]
> 
> 
> I have had a look using Laravel v6.15.1 but wasn't able to replicate the issue.
> 
> @simplenotezy Which version of Laravel are you using?

I've added a couple of test cases for single route handling and wasn't able to replicate the issue either. 
@simplenotezy could you provide more info like your configs so that tests can be more precise

**Comment by Micky5991** [comment]
I also have this issue with Postwoman.io. 

If I add the Cors middleware to my global middleware stack in the HTTP Kernel, it works fine. 
But, if I try to add it just to my group of routes, the api for example, it does not work anymore. 

After some investigation, it seems that this middleware won't be applied unless you explicitly add the Cors middleware to the `OPTIONS` method, but for preflight it is needed to be available and correctly set up.

```php
Route::options('/', function () { return null; });
```

In my use case I just want to set the CORS headers to my api part of my application, but not the rest of it.

**Comment by Sadegh-Ameri** [comment]
I couldn't replicate the issue.
Laravel version is `v6.16.0`.
spatie/laravel-cors is `1.6.0`.
Not sure if it is important, I'm running on Laravel on default Laradock containers.
In `app/Http/Kernel.php` I added
```
protected $routeMiddleware = [
.
.
.
        'cors' => \Spatie\Cors\Cors::class,
    ];
```

In `routes/web.php`, I added 2 test routes.
```
Route::get('/test1', function () {
    return 'test1';
})->middleware('cors');

Route::get('/test2', function () {
    return 'test2';
});
```
I'm testing the routes by calling the website from a simple html file.
```
<!DOCTYPE html>
<html>
<head>
    <title>CORS Test</title>
</head>
<body>
<h2>CORS Test</h2>
<button onclick="test1()">Test 1</button>
<button onclick="test2()">Test 2</button>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script>
    function test1() {
        axios.get('http://localhost/test1')
            .then(function (response) {
                console.log('Test 1: ' + response.data);
            });
    }

    function test2() {
        axios.get('http://localhost/test2')
            .then(function (response) {
                console.log('Test 2: ' + response.data);
            });
    }
</script>
</body>
</html>
```
This is the result I receive
![cors_test](https://user-images.githubusercontent.com/19542679/75100589-02fe4c00-55d0-11ea-9c6c-ebd187df9bec.png)

Appreciate if you could provide more info so we can reproduce the issue.

**Comment by simplenotezy** [comment]
>I couldn't replicate the issue. ...

@Sadegh-Ameri first of all, your screenshot clearly shows a CORS error. So it seems like you produced it just fine. Secondly, I'm not sure whether CORS applies to HTML files, but perhaps it does.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sadegh-Ameri** [comment]
> > I couldn't replicate the issue. ...
> 
> @Sadegh-Ameri first of all, your screenshot clearly shows a CORS error. So it seems like you produced it just fine. Secondly, I'm not sure whether CORS applies to HTML files, but perhaps it does.
> 
> Sent with [GitHawk](http://githawk.com)

@simplenotezy In my route file, I'm using the `cors` middleware only on the `/test1`. In `/test2`, `cors` middleware is not included. That's why I am receiving the cors error only on the `/test2`.
I did this test because you wanted to enable cors only for some routes and not all of them.

If I enable cors for `/test2`, I do not receive the cors error anymore.
```
Route::get('/test1', function () {
    return 'test1';
})->middleware('cors');

Route::get('/test2', function () {
    return 'test2';
})->middleware('cors');
```
![cors_test2](https://user-images.githubusercontent.com/19542679/75190602-eb9a9c80-5750-11ea-8dce-2d20e6bec42c.png)

**Comment by simplenotezy** [comment]
It doesn't matter. Laravel 7 comes with this built in

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by freekmurze** [comment]
Thank you for reporting this, but we're not going to invest time in a fix.

Laravel 7 introduced native support for CORS. We are going to abandon our package. Please upgrade to Laravel 7.
