### ISSUE TITLE
same origin gets blocked if not specified in allow_origins

### ISSUE THREAD

**Issue by mberneis** [spatie/laravel-cors#77]
I have a main app `main` which also provides an API to serve another app `secondary`.
I configured cors and added `secondary` into the `allow_origins` array. 

But now internal calls in `main` get also blocked. - I need to add the `main` URL also to the `allow_origins` array. - Shouldn't internal calls always go through?

**Comment by freekmurze** [comment]
Thank you for reporting this, but we're not going to invest time in a fix.

Laravel 7 introduced native support for CORS. We are going to abandon our package. Please upgrade to Laravel 7.
